import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
import type {SidebarItemConfig} from '@docusaurus/plugin-content-docs/lib/sidebars/types';

// Docusaurus i18n generates translation keys from category labels. When multiple
// sidebar sections (tutorials, guides) share category names like "Get started" or
// "Qiskit Functions", the keys collide and the build fails. This collects all
// category labels from one section, then renames collisions in another section.
function collectCategoryLabels(items: SidebarItemConfig[], labels: Set<string> = new Set()): Set<string> {
  for (const item of items) {
    if (typeof item === 'object' && 'type' in item && item.type === 'category') {
      const cat = item as {label: string; items?: SidebarItemConfig[]};
      labels.add(cat.label);
      if (cat.items) collectCategoryLabels(cat.items, labels);
    }
  }
  return labels;
}

function deduplicateLabels(items: SidebarItemConfig[], existing: Set<string>, suffix: string): SidebarItemConfig[] {
  return items.map((item) => {
    if (typeof item === 'object' && 'type' in item && item.type === 'category') {
      const cat = item as {type: 'category'; label: string; items: SidebarItemConfig[]; [k: string]: unknown};
      const dedupedItems = cat.items ? deduplicateLabels(cat.items, existing, suffix) : [];
      if (existing.has(cat.label)) {
        return {...cat, label: `${cat.label} (${suffix})`, items: dedupedItems};
      }
      return {...cat, items: dedupedItems};
    }
    return item;
  });
}

// Import generated sidebar structures from sync-content.py
// Falls back to autogenerated/empty if sync hasn't run yet
let tutorialItems: SidebarItemConfig[];
try {
  tutorialItems = require('./sidebar-generated.json');
} catch {
  tutorialItems = [{type: 'autogenerated', dirName: 'tutorials'}];
}

let guideItems: SidebarItemConfig[];
try {
  guideItems = require('./sidebar-guides.json');
} catch {
  guideItems = [];
}

let courseItems: SidebarItemConfig[];
try {
  courseItems = require('./sidebar-courses.json');
} catch {
  courseItems = [];
}

let moduleItems: SidebarItemConfig[];
try {
  moduleItems = require('./sidebar-modules.json');
} catch {
  moduleItems = [];
}

let addonItems: SidebarItemConfig[];
try {
  addonItems = require('./sidebar-addons.json');
} catch {
  addonItems = [];
}

// Collect tutorial category labels so we can rename collisions in guides
const tutorialLabels = collectCategoryLabels(tutorialItems);

const sidebars: SidebarsConfig = {
  tutorialsSidebar: [
    {
      type: 'link',
      label: 'Home',
      href: '/',
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      link: {type: 'doc', id: 'tutorials/index'},
      items: tutorialItems,
    },
    ...(guideItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Guides',
            collapsed: true,
            link: {type: 'doc' as const, id: 'guides/index'},
            items: deduplicateLabels(guideItems, tutorialLabels, 'Guides'),
          },
        ]
      : []),
    ...(courseItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Courses',
            collapsed: true,
            items: courseItems,
          },
        ]
      : []),
    ...(moduleItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Modules',
            collapsed: true,
            items: moduleItems,
          },
        ]
      : []),
    /* API Reference + Settings are in the navbar — not duplicated here */
  ],
  // Qiskit Addons live in their own sidebar so the pages are still built and
  // have working navigation when visited by direct URL, but they do NOT appear
  // in the main tutorialsSidebar or the navbar. Re-enable by adding a navbar
  // entry in docusaurus.config.ts and/or splicing the category back into
  // tutorialsSidebar above.
  ...(addonItems.length > 0
    ? {
        qiskitAddonsSidebar: [
          {
            type: 'category' as const,
            label: 'Qiskit Addons',
            collapsed: false,
            link: {type: 'doc' as const, id: 'qiskit-addons/index'},
            items: addonItems,
          },
        ],
      }
    : {}),
  // Workshop notebooks — accessible via /workshop/{name} but not in navbar.
  // Instructors add notebooks to docs/workshop/ for hands-on sessions.
  workshopSidebar: [
    {
      type: 'autogenerated' as const,
      dirName: 'workshop',
    },
  ],
};

export default sidebars;
