import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Import generated sidebar structures from sync-content.py
// Falls back to autogenerated/empty if sync hasn't run yet
let tutorialItems: SidebarsConfig[string];
try {
  tutorialItems = require('./sidebar-generated.json');
} catch {
  tutorialItems = [{type: 'autogenerated', dirName: 'tutorials'}];
}

let guideItems: any[];
try {
  guideItems = require('./sidebar-guides.json');
} catch {
  guideItems = [];
}

let courseItems: any[];
try {
  courseItems = require('./sidebar-courses.json');
} catch {
  courseItems = [];
}

let moduleItems: any[];
try {
  moduleItems = require('./sidebar-modules.json');
} catch {
  moduleItems = [];
}

const sidebars: SidebarsConfig = {
  tutorialsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: true,
      link: {type: 'doc', id: 'tutorials/index'},
      items: tutorialItems as any[],
    },
    ...(guideItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Guides',
            collapsed: true,
            link: {type: 'doc' as const, id: 'guides/index'},
            items: guideItems,
          },
        ]
      : []),
    ...(courseItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Courses',
            collapsed: true,
            items: courseItems,
          },
        ]
      : []),
    ...(moduleItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Modules',
            collapsed: true,
            items: moduleItems,
          },
        ]
      : []),
    {
      type: 'link' as const,
      label: 'API Reference',
      href: 'https://quantum.cloud.ibm.com/docs/en/api',
    },
  ],
};

export default sidebars;
