import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Import generated sidebar structures from sync-content.py
// Falls back to autogenerated/empty if sync hasn't run yet
let tutorialItems: SidebarsConfig[string];
try {
  tutorialItems = require('./sidebar-generated.json');
} catch {
  tutorialItems = [{type: 'autogenerated', dirName: 'tutorials'}];
}

let courseItems: any[];
try {
  courseItems = require('./sidebar-courses.json');
} catch {
  courseItems = [];
}

const sidebars: SidebarsConfig = {
  tutorialsSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'Tutorials',
      collapsed: false,
      link: {type: 'doc', id: 'tutorials/index'},
      items: tutorialItems as any[],
    },
    ...(courseItems.length > 0
      ? [
          {
            type: 'category' as const,
            label: 'Courses',
            collapsed: false,
            items: courseItems,
          },
        ]
      : []),
  ],
};

export default sidebars;
