#!/usr/bin/env python3
"""Measure, per locale, which house-style terms the translations keep in English.

The 2026-09-08 house style kept one list of terms in English for every
locale (_common.KEEP_ENGLISH_TERMS). The corpus disagrees by locale: es/fr/ar
translate "gate" in >90% of its occurrences while id/th/tl keep it >97%, so
new pages written to the shared list read unlike the rest of their site
(es new pages: "circuit" left English 68% of the time vs 13% elsewhere).

For each candidate term this counts its occurrences in the English msgid
(outside code, links, tags and anchors) and how many survive in the msgstr.
A term a locale keeps in at least half of its occurrences stays English for
that locale; below that the locale translates it. The result is written to
translation/v2/kept-english.json, which translate.py, fix.py and the
deep-review leak filter read through _common.kept_english_terms(locale).

    python3 translation/scripts/measure-kept-english.py          # print
    python3 translation/scripts/measure-kept-english.py --write  # + JSON

Re-run after large translation changes; the JSON records the percentages so
a reviewer can see how close to the threshold a term is.
"""
from __future__ import annotations

import argparse
import collections
import json
import re
import sys
from pathlib import Path

import polib

REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO / "translation" / "scripts"))
from _common import ALWAYS_ENGLISH, KEEP_ENGLISH_TERMS, KEPT_ENGLISH_JSON  # noqa: E402

THRESHOLD = 50  # percent of occurrences kept in English
MEASURED = [t for t in KEEP_ENGLISH_TERMS if t not in ALWAYS_ENGLISH]
_STRIP = re.compile(r"`[^`]*`|\]\([^)]*\)|<[^>]*>|\{#[^}]*\}")


def measure(locale: str) -> dict[str, int]:
    src: collections.Counter = collections.Counter()
    kept: collections.Counter = collections.Counter()
    for p in sorted((REPO / "i18n" / locale / "po").rglob("*.po")):
        for e in polib.pofile(str(p), wrapwidth=0):
            if not e.msgstr or e.obsolete or "fuzzy" in e.flags:
                continue
            a, b = _STRIP.sub("", e.msgid), _STRIP.sub("", e.msgstr)
            for t in MEASURED:
                rx = r"\b" + re.escape(t) + r"s?\b"
                n = len(re.findall(rx, a, re.I))
                if n:
                    src[t] += n
                    kept[t] += min(n, len(re.findall(rx, b, re.I)))
    return {t: (100 * kept[t] // src[t]) if src[t] else 100 for t in MEASURED}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[1])
    ap.add_argument("--write", action="store_true", help=f"write {KEPT_ENGLISH_JSON.relative_to(REPO)}")
    args = ap.parse_args()
    locales = sorted(d.name for d in (REPO / "i18n").iterdir() if (d / "po").is_dir())
    out = {"_note": ("Generated by translation/scripts/measure-kept-english.py. Per locale: the "
                     f"house-style terms its translations keep in English (>= {THRESHOLD}% of "
                     "occurrences), plus the measured percentage per term. "
                     f"{', '.join(ALWAYS_ENGLISH)} are English everywhere and not measured."),
           "threshold": THRESHOLD, "locales": {}}
    print("loc  " + " ".join(f"{t[:9]:>10}" for t in MEASURED))
    for loc in locales:
        pct = measure(loc)
        out["locales"][loc] = {"keep": [t for t in MEASURED if pct[t] >= THRESHOLD], "percent": pct}
        print(f"{loc:4} " + " ".join(f"{pct[t]:>9}%" for t in MEASURED))
    if args.write:
        KEPT_ENGLISH_JSON.write_text(json.dumps(out, indent=1, ensure_ascii=False) + "\n", encoding="utf-8")
        print(f"\nwrote {KEPT_ENGLISH_JSON.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
