// Auto-generated by scripts/sync-content.py — do not edit manually.
// Upstream commit + date represent the actual content version, not the sync run time.
export const UPSTREAM_COMMIT = 'be9f5739ac';
export const UPSTREAM_COMMIT_DATE = '2026-07-22';
