#!/bin/bash
#
# setup-pi.sh - Setup RasQberry for hosting Qiskit tutorials
#
# This script:
# 1. Installs and configures Jupyter server
# 2. Sets up nginx to serve the static site
# 3. Creates systemd services for auto-start
#
# Usage:
#   ./scripts/setup-pi.sh
#
# Requirements:
#   - Raspberry Pi OS (64-bit recommended)
#   - RQB2 Python virtual environment with Qiskit installed
#   - sudo privileges

set -e

# Configuration
VENV_PATH="${VENV_PATH:-/home/pi/RQB2}"
INSTALL_DIR="${INSTALL_DIR:-/opt/rasqberry-tutorials}"
TUTORIALS_DIR="${TUTORIALS_DIR:-/home/pi/tutorials}"
JUPYTER_PORT="${JUPYTER_PORT:-8888}"
JUPYTER_TOKEN="${JUPYTER_TOKEN:-$(python3 -c 'import secrets; print(secrets.token_hex(16))')}"
WEB_PORT="${WEB_PORT:-80}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

echo_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
echo_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
echo_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check if running as root
check_root() {
    if [ "$EUID" -eq 0 ]; then
        echo_error "Please run without sudo. The script will request sudo when needed."
        exit 1
    fi
}

# Check prerequisites
check_prerequisites() {
    echo_info "Checking prerequisites..."
    
    # Check for Python venv
    if [ ! -d "$VENV_PATH" ]; then
        echo_error "Python virtual environment not found at $VENV_PATH"
        echo_info "Please create it first or set VENV_PATH environment variable"
        exit 1
    fi
    
    # Check for pip in venv
    if [ ! -f "$VENV_PATH/bin/pip" ]; then
        echo_error "pip not found in virtual environment"
        exit 1
    fi
    
    # Check for Qiskit
    if ! "$VENV_PATH/bin/python" -c "import qiskit" 2>/dev/null; then
        echo_warn "Qiskit not found in virtual environment"
        echo_info "Installing Qiskit... (this may take a while)"
        "$VENV_PATH/bin/pip" install qiskit qiskit-aer
    fi
    
    echo_info "Prerequisites OK"
}

# Install Jupyter
install_jupyter() {
    echo_info "Installing Jupyter server..."
    
    "$VENV_PATH/bin/pip" install --upgrade \
        jupyter-server \
        jupyterlab \
        notebook
    
    echo_info "Jupyter installed"
}

# Configure Jupyter
configure_jupyter() {
    echo_info "Configuring Jupyter server..."
    
    # Create config directory
    mkdir -p ~/.jupyter
    
    # Generate config
    "$VENV_PATH/bin/jupyter" server --generate-config -y 2>/dev/null || true
    
    # Write configuration (quoted heredoc prevents shell injection)
    cat > ~/.jupyter/jupyter_server_config.py << 'PYEOF'
# doQumentation - Jupyter Server Configuration
# Generated by setup-pi.sh

c.ServerApp.token = '__TOKEN__'
c.ServerApp.password = ''
c.ServerApp.allow_origin = '*'
c.ServerApp.allow_remote_access = True
c.ServerApp.ip = '0.0.0.0'
c.ServerApp.port = __PORT__
c.ServerApp.open_browser = False
c.ServerApp.root_dir = '__TUTORIALS_DIR__'

# CORS settings for Thebe
c.ServerApp.allow_credentials = True
c.ServerApp.disable_check_xsrf = True
c.ServerApp.tornado_settings = {
    'headers': {
        'Access-Control-Allow-Origin': '*',
        'Access-Control-Allow-Methods': 'GET, POST, PUT, DELETE, OPTIONS',
        'Access-Control-Allow-Headers': 'accept, content-type, authorization, x-xsrftoken',
    }
}

# Resource management for trade show stability
c.MappingKernelManager.cull_idle_timeout = 600  # Kill idle kernels after 10 min
c.MappingKernelManager.cull_interval = 120      # Check every 2 min
c.MappingKernelManager.cull_connected = False   # Don't kill connected kernels
PYEOF
    # Substitute variables safely (sed, not shell expansion)
    sed -i "s|__TOKEN__|${JUPYTER_TOKEN}|g" ~/.jupyter/jupyter_server_config.py
    sed -i "s|__PORT__|${JUPYTER_PORT}|g" ~/.jupyter/jupyter_server_config.py
    sed -i "s|__TUTORIALS_DIR__|${TUTORIALS_DIR}|g" ~/.jupyter/jupyter_server_config.py
    
    echo_info "Jupyter configured"
}

# Create tutorials directory
setup_tutorials_dir() {
    echo_info "Setting up tutorials directory..."
    
    mkdir -p "$TUTORIALS_DIR"
    
    # Copy notebooks if they exist in install directory
    if [ -d "$INSTALL_DIR/notebooks" ]; then
        cp -r "$INSTALL_DIR/notebooks/"* "$TUTORIALS_DIR/" 2>/dev/null || true
        echo_info "Copied notebooks to $TUTORIALS_DIR"
    fi
    
    echo_info "Tutorials directory ready"
}

# Create systemd service for Jupyter
create_jupyter_service() {
    echo_info "Creating Jupyter systemd service..."
    
    sudo tee /etc/systemd/system/jupyter-tutorials.service > /dev/null << EOF
[Unit]
Description=Jupyter Server for doQumentation
After=network.target

[Service]
Type=simple
User=$USER
Environment="PATH=${VENV_PATH}/bin:/usr/local/bin:/usr/bin:/bin"
WorkingDirectory=${TUTORIALS_DIR}
ExecStart=${VENV_PATH}/bin/jupyter server
Restart=always
RestartSec=10

# Security hardening
NoNewPrivileges=true
ProtectSystem=strict
ProtectHome=read-only
ReadWritePaths=${TUTORIALS_DIR}
PrivateTmp=true

[Install]
WantedBy=multi-user.target
EOF
    
    sudo systemctl daemon-reload
    sudo systemctl enable jupyter-tutorials
    sudo systemctl restart jupyter-tutorials
    
    echo_info "Jupyter service created and started"
}

# Install and configure nginx
setup_nginx() {
    echo_info "Setting up nginx..."
    
    # Install nginx if not present
    if ! command -v nginx &> /dev/null; then
        sudo apt-get update
        sudo apt-get install -y nginx
    fi
    
    # Create nginx configuration
    sudo tee /etc/nginx/sites-available/rasqberry-tutorials > /dev/null << EOF
# doQumentation - nginx configuration

server {
    listen ${WEB_PORT};
    listen [::]:${WEB_PORT};
    server_name rasqberry.local tutorials.local _;

    # Static site root
    root ${INSTALL_DIR};
    index index.html;

    # Main site
    location / {
        try_files \$uri \$uri/ /index.html;
        
        # Cache static assets
        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2)$ {
            expires 1d;
            add_header Cache-Control "public, immutable";
        }
    }

    # Jupyter server proxy
    location /jupyter/ {
        proxy_pass http://127.0.0.1:${JUPYTER_PORT}/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_read_timeout 86400;
    }

    # WebSocket support for Jupyter
    location ~* /jupyter/(api/kernels/[^/]+/(channels|iopub|shell|stdin)|terminals/websocket) {
        proxy_pass http://127.0.0.1:${JUPYTER_PORT};
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }
}
EOF
    
    # Enable site
    sudo ln -sf /etc/nginx/sites-available/rasqberry-tutorials /etc/nginx/sites-enabled/
    
    # Remove default site if exists
    sudo rm -f /etc/nginx/sites-enabled/default
    
    # Test and reload nginx
    sudo nginx -t
    sudo systemctl enable nginx
    sudo systemctl reload nginx
    
    echo_info "nginx configured and started"
}

# Print final status and instructions
print_summary() {
    echo ""
    echo "========================================"
    echo "  doQumentation Setup Complete!"
    echo "========================================"
    echo ""
    
    # Get IP address
    IP_ADDR=$(hostname -I | awk '{print $1}')
    
    echo "Access the tutorials at:"
    echo "  • http://rasqberry.local"
    echo "  • http://${IP_ADDR}"
    echo ""
    echo "JupyterLab (for advanced users):"
    echo "  • http://rasqberry.local:${JUPYTER_PORT}/lab"
    echo "  • Token: ${JUPYTER_TOKEN}"
    echo ""
    echo "Service commands:"
    echo "  • sudo systemctl status jupyter-tutorials"
    echo "  • sudo systemctl restart jupyter-tutorials"
    echo "  • sudo journalctl -u jupyter-tutorials -f"
    echo ""
    echo "Tutorials directory: ${TUTORIALS_DIR}"
    echo ""
}

# Main
main() {
    echo ""
    echo "========================================"
    echo "  doQumentation - Pi Setup"
    echo "========================================"
    echo ""
    
    check_root
    check_prerequisites
    install_jupyter
    configure_jupyter
    setup_tutorials_dir
    create_jupyter_service
    setup_nginx
    print_summary
}

# Run main function
main "$@"
