#!/usr/bin/env python3
"""Sync binder/jupyter-requirements*.txt from upstream.

Reads the canonical requirements from
Qiskit/documentation/scripts/nb-tester/requirements.txt
and applies exception rules for our multi-arch Docker images:
  - Drop sys.platform markers (Linux-only containers)
  - Add pylatexenc (needed for LaTeX in Qiskit visualizations)
  - Move to amd64-only: gem-suite, qiskit-ibm-transpiler[ai-local-mode],
    qiskit-addon-aqc-tensor[quimb-jax] (no arm64 wheels)
  - Split qiskit-addon-aqc-tensor extras: [aer] cross-platform, [quimb-jax] amd64-only
  - Never downgrade: if our current pin is HIGHER than upstream's (e.g. a
    Dependabot security/version bump upstream hasn't picked up yet), the local
    pin is kept. This stops the weekly sync from silently reverting Dependabot
    (the sqd/scipy oscillation). A genuine upstream bump (upstream > local) is
    still adopted.

Usage:
    python scripts/sync-deps.py [upstream-requirements.txt]

If no file is given, fetches from GitHub directly.
"""

import re
import sys
import urllib.request
from pathlib import Path

UPSTREAM_URL = (
    "https://raw.githubusercontent.com/Qiskit/documentation"
    "/main/scripts/nb-tester/requirements.txt"
)

# Packages that go to amd64-only file (no arm64 wheels)
AMD64_ONLY = {"gem-suite", "qiskit-ibm-transpiler"}

# Extra split: qiskit-addon-aqc-tensor[aer] is cross-platform,
# [quimb-jax] is amd64-only (kahypar has no arm64 wheel)
AQC_TENSOR = "qiskit-addon-aqc-tensor"

# Packages we add that aren't in upstream
EXTRA_CROSS_PLATFORM = ["pylatexenc", "pandas"]

CROSS_PLATFORM_HEADER = """\
# WARNING: This file is auto-generated by scripts/sync-deps.py
# DO NOT EDIT MANUALLY - changes will be overwritten!
#
# Full Qiskit dependencies for Docker / local Jupyter (both amd64 and arm64).
# Synced with Qiskit/documentation/scripts/nb-tester/requirements.txt.
# amd64-only extras are in jupyter-requirements-amd64.txt.
# Exceptions vs upstream:
#   - pylatexenc added (needed for LaTeX in Qiskit visualizations)
#   - pandas added (used by 11 notebooks for data analysis)
#   - gem-suite moved to amd64-only (no arm64 prebuilt wheel)
#   - sys.platform markers dropped (Linux-only container)
"""

AMD64_HEADER = """\
# WARNING: This file is auto-generated by scripts/sync-deps.py
# DO NOT EDIT MANUALLY - changes will be overwritten!
#
# Extra packages for amd64 only (no Linux arm64 wheels available).
# Installed conditionally in Dockerfile.jupyter.
"""

# Regex: package[extras]~=version; marker
LINE_RE = re.compile(
    r"^(?P<name>[a-zA-Z0-9_-]+)"
    r"(?:\[(?P<extras>[^\]]+)\])?"
    r"(?P<version>[^;#\s]+)?"
    r"(?:\s*;\s*(?P<marker>[^#]+))?"
    r"\s*(?:#.*)?$"
)


def parse_upstream(text: str) -> list[dict]:
    """Parse upstream requirements.txt into structured entries."""
    entries = []
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = LINE_RE.match(line)
        if not m:
            print(f"  Warning: could not parse line: {line}")
            continue
        entries.append({
            "name": m.group("name"),
            "extras": m.group("extras") or "",
            "version": (m.group("version") or "").strip(),
            "marker": (m.group("marker") or "").strip(),
        })
    return entries


# Extract a comparable version from a specifier string ("~=1.18.0" -> 1.18.0).
# Prefer packaging.version (handles pre/dev releases); fall back to an int-tuple.
try:
    from packaging.version import Version as _V

    def _ver(spec: str):
        m = re.search(r"[0-9][^,;\s]*", spec or "")
        try:
            return _V(m.group(0)) if m else None
        except Exception:
            return None
except ImportError:  # pragma: no cover - packaging is normally present
    def _ver(spec: str):
        m = re.search(r"\d+(?:\.\d+)*", spec or "")
        return tuple(int(x) for x in m.group(0).split(".")) if m else None


def load_local_versions(*paths: Path) -> dict[str, str]:
    """Map package name -> current local version specifier from existing files."""
    local: dict[str, str] = {}
    for path in paths:
        try:
            text = path.read_text()
        except FileNotFoundError:
            continue
        for line in text.splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            m = LINE_RE.match(line)
            if not m:
                continue
            version = (m.group("version") or "").strip()
            if version:
                # A package may appear in both files (aqc-tensor split); the
                # version is the same, so first-wins is fine.
                local.setdefault(m.group("name"), version)
    return local


def choose_version(name: str, upstream_version: str, local_map: dict[str, str]) -> str:
    """Return upstream_version, unless our local pin is higher (never downgrade)."""
    local_version = local_map.get(name)
    if not local_version or not upstream_version:
        return upstream_version
    lv, uv = _ver(local_version), _ver(upstream_version)
    if lv is None or uv is None:
        return upstream_version
    if lv > uv:
        print(
            f"  Keeping local pin {name}{local_version} "
            f"(upstream {upstream_version}) — no downgrade"
        )
        return local_version
    return upstream_version


def apply_rules(
    entries: list[dict], local_map: dict[str, str] | None = None
) -> tuple[list[str], list[str]]:
    """Apply exception rules, return (cross_platform_lines, amd64_lines)."""
    local_map = local_map or {}
    cross = []
    amd64 = []

    for e in entries:
        name, extras = e["name"], e["extras"]
        # Never downgrade below our current local pin (see module docstring).
        version = choose_version(name, e["version"], local_map)

        # Special case: qiskit-addon-aqc-tensor — split extras
        if name == AQC_TENSOR:
            extra_list = [x.strip() for x in extras.split(",")]
            cross_extras = [x for x in extra_list if x != "quimb-jax"]
            amd64_extras = [x for x in extra_list if x == "quimb-jax"]
            if cross_extras:
                cross.append(f"{name}[{','.join(cross_extras)}]{version}")
            if amd64_extras:
                amd64.append(
                    f"{name}[{','.join(amd64_extras)}]{version}"
                    "   # adds kahypar (no arm64 wheel)"
                )
            continue

        # amd64-only packages
        if name in AMD64_ONLY:
            fmt = f"{name}{version}" if not extras else f"{name}[{extras}]{version}"
            amd64.append(fmt)
            if name == "gem-suite":
                cross.append(
                    "# gem-suite: amd64 only (see jupyter-requirements-amd64.txt)"
                )
            continue

        # Regular package — drop markers, add to cross-platform
        fmt = f"{name}{version}" if not extras else f"{name}[{extras}]{version}"
        cross.append(fmt)

    # Add our extras not in upstream
    for pkg in EXTRA_CROSS_PLATFORM:
        cross.append(pkg)

    return cross, amd64


def write_file(path: Path, header: str, lines: list[str]) -> bool:
    """Write requirements file. Returns True if content changed."""
    content = header + "\n" + "\n".join(lines) + "\n"
    try:
        old = path.read_text()
    except FileNotFoundError:
        old = ""
    if content == old:
        return False
    path.write_text(content)
    return True


def main():
    # Get upstream requirements
    if len(sys.argv) > 1:
        upstream_text = Path(sys.argv[1]).read_text()
        print(f"Reading upstream from {sys.argv[1]}")
    else:
        print(f"Fetching upstream from {UPSTREAM_URL}")
        with urllib.request.urlopen(UPSTREAM_URL) as resp:
            upstream_text = resp.read().decode()

    entries = parse_upstream(upstream_text)
    print(f"  Parsed {len(entries)} packages from upstream")

    binder_dir = Path(__file__).resolve().parent.parent / "binder"
    cross_path = binder_dir / "jupyter-requirements.txt"
    amd64_path = binder_dir / "jupyter-requirements-amd64.txt"

    # Load current pins first so we never downgrade below them.
    local_map = load_local_versions(cross_path, amd64_path)
    cross_lines, amd64_lines = apply_rules(entries, local_map)

    cross_changed = write_file(cross_path, CROSS_PLATFORM_HEADER, cross_lines)
    amd64_changed = write_file(amd64_path, AMD64_HEADER, amd64_lines)

    if cross_changed or amd64_changed:
        print("\nFiles updated:")
        if cross_changed:
            print(f"  {cross_path}")
        if amd64_changed:
            print(f"  {amd64_path}")
    else:
        print("\nNo changes — already in sync with upstream.")


if __name__ == "__main__":
    main()
